
defun test
{
  panic "this is a test_error running"
}

inv test
